//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_ModuleFormInstance
    {
        public string F_Id { get; set; }
        public string F_FormId { get; set; }
        public string F_ObjectId { get; set; }
        public string F_InstanceJson { get; set; }
        public Nullable<int> F_SortCode { get; set; }
        public Nullable<System.DateTime> F_CreatorTime { get; set; }
        public string F_CreatorUserId { get; set; }
    }
}
